### ISSUE TITLE
Feature request: put-if-absent

### ISSUE THREAD

**Issue by vemv** [mpneuried/nodecache#100]
Hi!

Neat library, kudos ✌️

It seems to lack a PIF operation? Like https://apidock.com/rails/ActiveSupport/Cache/Store/fetch:

```
cache.fetch('city') do
  'Duckburgh'
end
```

^ That code tries a 'get' over the `city`key, executing the do...end block (basically, a function) if no key was set, setting the block's return value as the value to store.

Suggested nodecache syntax:

`myCache.fetch("some_key", fallbackComputation, 4) // key, fallback function, ttl`

WDYT?

Cheers - Victor

**Comment by AlexShkunov** [comment]
in some cases, load / fetch function can be provided even to a constructor.

**Comment by erdii** [comment]
Currently this is out of project scope as we are trying to reduce functionality "bloat" and code.
