### ISSUE TITLE
Wrong node_cache.js packaged in version 4.1.1

### ISSUE THREAD

**Issue by florian-koenig** [mpneuried/nodecache#101]
`npm install node-cache` provided me with the current version 4.1.1, as visible in the downloaded `node_modules/node-cache/package.json`. However, in `lib/node_cache.js` it says `node-cache 4.1.0 ( 2016-12-21 )` in the header comment.

Also, the construction option `deleteOnExpire` doesn't have any effect, probably because it hasn't been implemented in this, wrongly included, version of the library. In the Coffee script source code of 4.1.1, however, I see that it is implemented.

**Comment by erdii** [comment]
version `4.2.0` has been released on npm! sorry for the delay 😞
