### ISSUE TITLE
listen on expired event but receive callback on wrong time

### ISSUE THREAD

**Issue by hugeleaf** [mpneuried/nodecache#105]
node v8.9.4
node-cache v4.2.0
```const NodeCache = require('node-cache');
const localCache = new NodeCache();

localCache.on('expired', function (key, value) {
    console.log(new Date(),'expired key:',key, 'history:',value);
});

let a = {a: 1, b: 2, c: 3};
localCache.set('myKey', a, 3);
console.log(new Date(),'set mykey');

setTimeout(function() {
    let time = new Date();
    console.log(time,'get mykey ttl:',localCache.getTtl('myKey'));
    console.log(time,'get mykey:',localCache.get('myKey'));
}, 1000);

setTimeout(function() {
    let time = new Date();
    console.log(time,'get mykey ttl:',localCache.getTtl('myKey'));
    console.log(time,'get mykey:',localCache.get('myKey'));
}, 2000);

setTimeout(function() {
    let time = new Date();
    console.log(time,'get mykey ttl:',localCache.getTtl('myKey'));
    console.log(time,'get mykey:',localCache.get('myKey'));
}, 5000);
```
-result------------------------------------------------------------------
2018-05-26T10:09:11.246Z 'set mykey'
2018-05-26T10:09:12.254Z 'get mykey ttl:' 1527329354244
2018-05-26T10:09:12.254Z 'get mykey:' { a: 1, b: 2, c: 3 }
2018-05-26T10:09:13.252Z 'get mykey ttl:' 1527329354244
2018-05-26T10:09:13.252Z 'get mykey:' { a: 1, b: 2, c: 3 }
2018-05-26T10:09:16.255Z 'expired key:' 'myKey' 'history:' { a: 1, b: 2, c: 3 }
2018-05-26T10:09:16.254Z 'get mykey ttl:' undefined
2018-05-26T10:09:16.254Z 'get mykey:' undefined
-problem---------------------------------------------------------------
why i get expired event after 5s but as ttl set 3s ?

**Comment by mpneuried** [comment]
Internally the module will check all keys every {options.checkperiod} seconds. Default is 600s.
An additional ttl check is done on every get(). So yo‘ll receive the expired event with the first get after the ttl. In your case at 5s.
The fix yor example it‘s possible to ser the option {checkperiod=1} to run the check every second.
But be careful, if theres a lot of data in nodecache a check every second could generate some load on your process.

Does this answer yor question?
