### ISSUE TITLE
Does getting a key reset the TTL?

### ISSUE THREAD

**Issue by ScottChapman** [mpneuried/nodecache#106]
Does the process of getting a key reset the TTL for that key? I am wondering if I can use thing to keep track of JWT tokens.

**Comment by erdii** [comment]
getting a key does not reset it's TTL, but your could use:

```javascript
let cacheKey = "foo";
let newTTL = 600;
// ...
let value = cache.get(cacheKey);
if (value != null) {
    cache.ttl(cacheKey, newTTL);
}
```

**Comment by ScottChapman** [comment]
Thanks!
