### ISSUE TITLE
ksize shows `NaN` after setting value with number key.

### ISSUE THREAD

**Issue by bobmk2** [mpneuried/nodecache#108]
Hi. I found this when I use `getStats()` for looking application's node statement.

`ksize` in stats is `NaN` after setting value with number key.

I think that this problem is resolved  by checking key's type at `_getKeyLength: ( key )` like to `_getValueLength: (value)`.
But, I'm concerned that the solution has a bad influence on performance 🤔  .
Do you have any ideas?

https://github.com/mpneuried/nodecache/blob/f68ba652869e4fba4b75b0718d84aa3dabf2cfe2/_src/lib/node_cache.coffee#L558-L562

in `node-cache/lib/node_cache.js`
```javascript
    NodeCache.prototype._getKeyLength = function(key) {
      return key.length;
    };
```

Now, I changed my code to set string key with header like `cache_${num}`, so I can look cache stats 😄 .

Thanks 🙏 

## check code

```javascript
const NodeCache = require('node-cache');
const cache = new NodeCache();

cache.getStats();
// output => { hits: 0, misses: 0, keys: 0, ksize: 0, vsize: 0 }

cache.set(123, 'test');
cache.getStats();
// output => { hits: 0, misses: 0, keys: 1, ksize: NaN, vsize: 4 }

cache.set('test_key', 'test_value');
cache.getStats();
// output => { hits: 0, misses: 0, keys: 2, ksize: NaN, vsize: 14 }

// because number.length is undefined and number + undefined is NaN
const num = 123;
console.log(num.length)
// output => undefined
console.log(0 + undefined);
// output => NaN
```

## version information

```shell
$ node -v
v6.11.5

$ npm -v
3.10.10

$ cat node_modules/node-cache/package.json| grep "version"
  "version": "4.2.0"
```

**Comment by mpneuried** [comment]
This change is valid. I will have a detailed look at it soon and generate an new version
