### ISSUE TITLE
Suggestion: Why setTimeout checkperiod instead of just checking expiration when fetching?

### ISSUE THREAD

**Issue by Jakobud** [mpneuried/nodecache#112]
I'm new to `nodecache` but I have a question about the `checkPeriod` functionality. From what I can tell in the code, in order to delete expired cache items, a `setTimeout` is set for each cache item that will manually delete variables.

Perhaps I'm misunderstanding something, but this seems like unnecessary processing overhead to me. Why don't you do this:

```
// pseudo-code
does cache exist for value?
  if (true)
    is cache expiration date < Date.now()
      if (true)
        get new value, cache it and return the value
      else
        return the cached value
  else
    get new value, cache it, and return the value
```

This way, you don't ever have to have individual `setTimeout` threads running in the background. You simply check the expiration before return cached values. If it's expired, then get a fresh value and return it. Otherwise just return what's cached since it's not expired yet.

Is the reason you are doing `setTimeouts` in the background because you are trying to minimize memory usage of cached items?

**Comment by Jakobud** [comment]
But then cached values would never expire, correct?

**Comment by erdii** [comment]
No. The cached values would be expires when you try to get them. It works exactly as described in your pseudocode. 👍

**Comment by Jakobud** [comment]
Oh I see excellent. Thanks!
