### ISSUE TITLE
Are there any risks of crash my Node.js app due to high memory usage?

### ISSUE THREAD

**Issue by y-zono** [mpneuried/nodecache#113]
Hi, this library is very useful and super easy to use it. However I have a concern whether there are any risks of crash my Node.js app due to high memory usage.

>All keys are stored in a single object so the practical limit is at around 1m keys.

According to README.md, seems there is the limitation. Then I checked my usage on test environment.

```
// myCache.getStats();
{ hits: 199, misses: 100, keys: 100, ksize: 4543, vsize: 27212 }
```

I guess that ksize and vsize mean data size (byte) and my each key and value size is almost same.

```
data size of 1 key = 4543 / 100 + 27212 / 100 = 317.55 bytes

317.55 bytes * 1m keys = 317.55 * 1000000 = 317550000 bytes = 317.55 megabytes
```

Therefor, I think maximum memory usage is about 317.55 MB in my case. Is my understanding correct?

This might be related.

https://github.com/mpneuried/nodecache/issues/63

**Comment by y-zono** [comment]
I think the answer is yes. Seems the maxCacheSize feature was added as TODO task. (see https://github.com/mpneuried/nodecache/issues/63)

I confirmed that memory was consumed until the maximum heap size of Node. (default is currently about 1.5GB?)

* index.js

```
const NodeCache = require( "node-cache" );
const myCache = new NodeCache();

const v = 'x'.repeat(300)

let i = 0;
while(1) {
  const k = "k" + Math.random();
  success = myCache.set(k, v);
  if(++i % 10000 === 0) {
    console.log(i);
    console.log(v);
    console.log(myCache.getStats());
    console.log(process.memoryUsage());
  }
}
```

* Result

```
$ node index.js

{ hits: 0,
  misses: 0,
  keys: 5590000,
  ksize: 107719021,
  vsize: 1677000000 }
{ rss: 1337618432,
  heapTotal: 1318977536,
  heapUsed: 1141257944,
  external: 8224 }

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by SUPERCILEX** [comment]
For other people doing the same research as me, you're probably looking for an LRU cache: https://www.npmjs.com/package/lru-cache
