### ISSUE TITLE
unit of stats

### ISSUE THREAD

**Issue by dzsessona** [mpneuried/nodecache#12]
Can I ask what is the unit of the ksize and vsize in the stats? I am displaying the stats in the admin section of my project and I would like to know it is over a certain amount of memory. 

![screen shot 2014-08-08 at 02 06 22](https://cloud.githubusercontent.com/assets/1695672/3851584/49a9b22c-1e98-11e4-9d32-5db555adbd43.png)

So I suppose i can check vsize+ksize, but what is the unit of those values? 

Btw thanks for this project, super useful.

**Comment by bdmcfarland7** [comment]
It would be nice to know this.  It would REALLY nice if you were able to specify a max memory usage!

**Comment by bryanspears** [comment]
I was glancing at issues and source to see if I wanted to use this module and the answer is right there in the source. He ballparks object/array size and uses known byte sizes for strings/numbers. So, your answer is: approximately bytes. :smile:

**Comment by klemensz** [comment]
Would be great if this information can be added to the README. Thanks!
