### ISSUE TITLE
why can "set" return a failure?

### ISSUE THREAD

**Issue by LiranBri** [mpneuried/nodecache#122]
Hello,
I see "Set" returns true/false, or have callback with "error" boolean flag.

when could it return "false" ? 
my guess is it could happen if we run out of memory or maximum capacity (if such thing exists)

thank you

**Comment by LiranBri** [comment]
answering myself: after just looking at the source code, it seems like the only way to fail is if the key is in wrong format (not number/string)

**Comment by erdii** [comment]
Also: One initial selling point of this library was the api compatibility to the [memcached npm module](https://www.npmjs.com/package/memcached)

Feel free to ask follow up questions if things are unclear! :)
