### ISSUE TITLE
Get return different parent class object

### ISSUE THREAD

**Issue by AmitThakkar** [mpneuried/nodecache#123]
When I use custom class(e.g. JSONSet is a child of Set) and setting to node-cache object, but when getting on node-cache, it returns me an object of parent class object in my case that is Set which does not have my override functions.

```
'use strict';

const NodeCache = require('node-cache');

class JSONSet extends Set {
    toJSON() {
        return [...this]
    }
}

let cache = new NodeCache({stdTTL: 60});

(async () => {
    const jsonSet = new JSONSet();
    jsonSet.add('3');
    jsonSet.add('4');

    await cache.set('myJSONSet', jsonSet);
    const jsonSet2 = await cache.get('myJSONSet');

    console.log(jsonSet); // JSONSet [Set] { '3', '4' }
    console.log(jsonSet2); // Set { '3', '4' }
})();
```

**Comment by erdii** [comment]
Woah crazy! I'll definitely have a look into that!

**Comment by erdii** [comment]
Ah... found it. NodeCache defaults to "clone-mode".

Replace
`let cache = new NodeCache({stdTTL: 60});`
with
`let cache = new NodeCache({stdTTL: 60, useClones: false});`

and it works fine. :)

**Comment by AmitThakkar** [comment]
It worked, thanks for helping me out.
