### ISSUE TITLE
Cache returning empty [] for mobx observable objects

### ISSUE THREAD

**Issue by rnagavar** [mpneuried/nodecache#125]
Node cache is returning mobx observable objects as empty array.

**Comment by mpneuried** [comment]
Hi i guess you should set the Option „useClones = false“.
More details are in the docs.
If this is not a solution for you specific problem, please provide a code example to reproduce the case quickly.

**Comment by erdii** [comment]
Closed due to inactivity.

Also I am pretty sure that useClones was the culprit.
