### ISSUE TITLE
Docs unclear regarding .getTtl

### ISSUE THREAD

**Issue by mullinb** [mpneuried/nodecache#126]
In the docs the following instructions are given:

```myCache.getTtl( key, [callback] )```

*Receive the ttl of a key. You will get:*

*undefined if the key does not exist*
*0 if this key has no ttl*
***a timestamp in ms until the key expires***

The wording of this last line is very confusing. As the timestamp returned by this method is not an *amount* of time *until* something expires, "until" is a very confusing word to use in this case. 

Please rewrite this line as follows:

*a Unix Time Stamp (e.g. 1456000600000) representing the time at which the key will expire*

Thank you.

**Comment by erdii** [comment]
PR welcome :)

**Comment by mullinb** [comment]
Hi erdii, I've never done a PR before. Thank you for the invitation to make one. As soon as I have time over the weekend I will go ahead and make one for this, wish me luck!

**Comment by erdii** [comment]
Nice! :) Shoot me a message if you need something - always glad to help someone boarding the open-source-contributor ship 😊
