### ISSUE TITLE
add a .has() method

### ISSUE THREAD

**Issue by regevbr** [mpneuried/nodecache#131]
Will be nice to have a `.has(key)` method like [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

**Comment by alexisab** [comment]
You can easily check if your cache has a key : `myCache.keys().includes('myKey')`

**Comment by regevbr** [comment]
@alexisab thanks that will solve it but the overhead of creating the keys object is too much...
```js
    NodeCache.prototype.keys = function(cb) {
      var _keys;
      _keys = Object.keys(this.data); // <====
      if (cb != null) {
        cb(null, _keys);
      }
      return _keys;
    };
```
We can add a method to do it in O(1)
```javascript
    NodeCache.prototype.has = function(key, cb) {
      var exists = this.data[key] != null;
      if (cb != null) {
        cb(null, exists);
      }
      return exists;
    };
```
What do you think?

**Comment by alexisab** [comment]
I think your solution won't work because what if I want to cache `null` or `undefined` for a given key ? Your function will return `false` instead of `true`.

We should use the `in` operator :

```js
NodeCache.prototype.has = function(key, cb) {
  var exists = key in this.data

  if (cb) {
    cb(null, exists)
  }

  return exists
}
```

**Comment by regevbr** [comment]
@alexisab from my understanding of the code, `data` holds oobjects that holds the value and the timestamp, and not the actual values, so my solution should work.

**Comment by alexisab** [comment]
Oh ! Ok :smile: ! I haven't read the sources in detail and I'm not really familiar with the coffee script

**Comment by regevbr** [comment]
@erdii do you think my solution is feasible?

**Comment by erdii** [comment]
woah nice activity here! 👍

Both solutions seem pretty nice, but there is one thing left to add:  A call to `this._check(key, this.data[key])` because otherwise we will get `true` for expired keys that have not been cleaned up yet.

What do you think about:

```js
NodeCache.prototype.has = function(key, cb) {
  const exists = this.data[key] != null &&  this._check(key, this.data[key]);
  if (cb != null) {
    cb(null, exists);
    return;
  }
  return exists;
};
```

I think we should also include this into nodecache itself.

**Comment by erdii** [comment]
PR #132 has landed! :)
