### ISSUE TITLE
Move `lodash` to `peerDependencies`

### ISSUE THREAD

**Issue by liyuanqiu** [mpneuried/nodecache#133]
We can see this page:
https://bundlephobia.com/result?p=node-cache@4.2.1

node-cache is about 22KB after minified without gzip, but `lodash` seizes about 15KB.
![image](https://user-images.githubusercontent.com/24999464/62020072-ffe6dd00-b1f3-11e9-9fed-148729f0cce0.png)

It's not very friendly to browsers.

So maybe it's better to move `lodash` from `dependencies` to `peerDependencies`, just use the one that users installed by themselves.

If accepted, I can raise a PR to do it.

**Comment by erdii** [comment]
Hey @liyuanqiu ! :) We are currently evalutating options for our new 5.x release. One major point is to remove the lodash dependency completely to avoid those 15k you noticed.

Thank you for your input!

PS: I'm closing this issue
