### ISSUE TITLE
Some more effective way to EXPIRE?

### ISSUE THREAD

**Issue by rhapsodyn** [mpneuried/nodecache#134]
`setTimeout` way to expire keys seems TOO raw, it's hard to decide the perfect interval.

Maybe the [redis style](https://redis.io/commands/expire#how-redis-expires-keys)?

I'm not a coffee-script guy, unable to pull request :frowning::frowning:

**Comment by erdii** [comment]
Currently this is out of project scope as we are trying to reduce functionality "bloat" and code.
