### ISSUE TITLE
cluster environment

### ISSUE THREAD

**Issue by adin234** [mpneuried/nodecache#21]
when using node-cache in a clustered environment. obviously, it will create n number of caches based on how many forks we create. i am trying to look for a way for the forked processes to just use one cache, the initial idea is to instantiate the cache on cluster.js and try to send the cache to the forks by using worker.send. the problem here is

```
var string = JSON.stringify(message) + '\n';
                      ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ChildProcess.target._send (child_process.js:479:23)
    at ChildProcess.target.send (child_process.js:416:12)
    at Worker.send (cluster.js:64:21)
```

**Comment by smrchy** [comment]
Of course one could think about this and let Node.js handle the propagation of all inserts/updates and deletes to the clustered environment. I guess that using a shared local memcached instance is the way to go here. Maybe it's a bit slower than Node but so much less headache.

**Comment by lvx3** [comment]
I've got a work in progress wrapper for just this - please try it out and let me know how you get on

http://github.com/lvx3/cluster-cache

**Comment by doublesharp** [comment]
I had a similar problem and wrote a wrapper for `lru-cache` to handle clustered environments using a cache on the master thread and IPC calls from the workers. Here is a link in case it's helpful to anyone else: https://www.npmjs.com/package/lru-cache-for-clusters-as-promised

**Comment by erdii** [comment]
Closed due to inactivity.
