### ISSUE TITLE
Make everything asynchronous 

### ISSUE THREAD

**Issue by DiegoRBaquero** [mpneuried/nodecache#56]
Right now the module is very synchronous with the callbacks and some code execution.

I'm mostly concerned about the TTL check period which goes through all the keys synchronously.

Everything should be deferred using `process.nextTick` / `setImmediate` / `setTimeout(fn,0)`

**Comment by feross** [comment]
That said, doing a process.nextTick() after every operation will add a ton of overhead and make the operation take a really long time.
