### ISSUE TITLE
Add StorageProvider

### ISSUE THREAD

**Issue by mpneuried** [mpneuried/nodecache#57]
Add a kind of storage setting to change the persistance from memory to for example a json file, the local storage or a custom storage provider.
This storage should have flag if all request must be called async

**Comment by julianxhokaxhiu** [comment]
Please consider it, I really need it for my project ( see https://github.com/julianxhokaxhiu/zeroads )

Thanks in advance!

**Comment by cinder92** [comment]
where it save cached objects? in localStorage or something?

**Comment by AnandChowdhary** [comment]
I made a library which uses a file system-based key-JSON storage, based on nodecache. The primary source is the file system (JSON files in a folder), but every key which is fetched is then saved in the cache. If you're still interested in having a file system storage for nodecache, check it out: https://github.com/AnandChowdhary/fraud/.

**Comment by erdii** [comment]
FS is out of current project scope.
