### ISSUE TITLE
NodeCache is not a constructor

### ISSUE THREAD

**Issue by jbeckton** [mpneuried/nodecache#59]
Not sure why I am getting this error...

`var NodeCache = require( "node-cache" );`

`var cache =  new NodeCache();`

produces error:

" NodeCache is not a constructor "

I am using Typescript as well but even when i use the same code from the examples provided, I get this error.

**Comment by mpneuried** [comment]
Hi,
I tried it with Tonic and it works fine...

https://tonicdev.com/573a14f6f2834f1100269d78/573a14f6f2834f1100269d79

Which version of node-cache and node do you use?
Which OS?
Never tried it with TypeScript, but i know that some people using node-cache within TypeScript. So in general it should work.

**Comment by jbeckton** [comment]
I am on nodejs 6.0.0

the only way I could get it to work is..

`let nc = require( "node-cache" );`

`let cache =  new nc.NodeCache();`

I am on CentOS 7

I found some typescript definitions for node-cache but they do not seem to help much with this issue.


when I console.log(nc) I get...

`{ NodeCache: 
   { [Function: NodeCache]
     EventEmitter: 
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: [Getter/Setter],
        init: [Function],
        listenerCount: [Function] },
     usingDomains: false,
     defaultMaxListeners: 10,
     init: [Function],
     listenerCount: [Function],
     __super__: 
      EventEmitter {
        domain: undefined,
        _events: undefined,
        _maxListeners: undefined,
        setMaxListeners: [Function: setMaxListeners],
        getMaxListeners: [Function: getMaxListeners],
        emit: [Function: emit],
        addListener: [Function: addListener],
        on: [Function: addListener],
        prependListener: [Function: prependListener],
        once: [Function: once],
        prependOnceListener: [Function: prependOnceListener],
        removeListener: [Function: removeListener],
        removeAllListeners: [Function: removeAllListeners],
        listeners: [Function: listeners],
        listenerCount: [Function: listenerCount],
        eventNames: [Function: eventNames] } },
  version: '3.2.1' }` 

which explains why I have to do new nc.NodeCache().

**Comment by jbeckton** [comment]
Here is the generated js file from typescript to commonjs format. It's just a wrapper around node-cache.


[eurekaCache.service.js.txt](https://github.com/tcs-de/nodecache/files/266880/eurekaCache.service.js.txt)

**Comment by jbeckton** [comment]
I happen to run across an article about Typescript namespaces and one of the pitfalls of them is the exact behavior that I have reported here. The guy that wrote the .d.ts (typescript definitions) created this due to the way he used the namespace in the definition file. There is most likely no issues with your library and you nay want to close this bug.

**Comment by mpneuried** [comment]
So it's not a bug ... right?
It's just a special handling required within Type-Script?

I don't know TypeScript so if i add [this information](https://github.com/tcs-de/nodecache/pull/40/commits/314769fecf1f7c6b086a638e862be0f82db2dd13#diff-04c6e90faac2675aa89e2176d2eec7d8R26) to the readme would it help you and others using typescript to use node-cache?

**Comment by jbeckton** [comment]
Well, as long as you reference that specific typescript definition file then yes it would help. A definition file could exist without the namespace and your readme addition would not make sense.

This issue only appears if the definition is installed that exports the namespace, Typescript devs can still use your library without the definitions. I have been trying to look for the definitions for all the third party modules I use but I am learning that not all of the defs are in sync with the module versions so sometimes I work without them.

Also mention that those who choose to use a typescript definition not maintained by you need to check the versions match up, I've had that bite me a few times.

Thanks

**Comment by bneiluj** [comment]
What about using `default` while importing the `node-cache` lib into your typescript? : 
```
var NodeCache  = require('node-cache').default;
var cache = new NodeCache();
```

**Comment by LarsLiden** [comment]
This seems to work nicely:

```
import * as NodeCache from 'node-cache';
let cache = new NodeCache();
```

**Comment by jaskinn** [comment]
Does anyone have any other suggestions? So far I haven't had any luck.

**Comment by nguyennhukhanh** [comment]
```
import NodeCache from 'node-cache';
const cache = new NodeCache();
```

**Comment by engr-mervin** [comment]
For anyone running into this issue, this worked for me:
```
import { default as NodeCache } from 'node-cache';

const cache = new NodeCache();
```

**Comment by Syno0** [comment]
Ok so I've been stuck for 6 hours on the subject. I'm using SWC and Typescript and my problem is that the esModuleInterop: true key was placed in the src/back/tsconfig.json file and not in ./tsconfig.json 
SWC only takes into account the tsconfig.json file in the project root...
So remember to place this esModuleInterop key in the right tsconfig file if you have several in your project.

**Comment by Syno0** [comment]
Ok so I've been stuck for 6 hours on the subject. I'm using SWC and Typescript and my problem is that the esModuleInterop: true key was placed in the src/back/tsconfig.json file and not in ./tsconfig.json 
SWC only takes into account the tsconfig.json file in the project root...
So remember to place this esModuleInterop key in the right tsconfig file if you have several in your project.
