### ISSUE TITLE
When setting new NodeCache({errorOnMissing:false}) still returns error

### ISSUE THREAD

**Issue by aloncarmel** [mpneuried/nodecache#60]
var cache = new NodeCache({errorOnMissing:false});

Still returns a throw error instead of undefined.

**Comment by mpneuried** [comment]
I tested it here and was not able to reproduce your issue:
https://tonicdev.com/56d037673a33ce0d001aefbd/573da6bd1afffd120012eafa

Can you update the tonic example or send me a functional code snippet, so i can reproduce it.

Thanks!
