### ISSUE TITLE
share the same cache between 2 nodejs script

### ISSUE THREAD

**Issue by kenpeter** [mpneuried/nodecache#61]
I set a cache key and store a value in one nodejs script. How do I use the same key and access the value in another nodejs script? Right now, it will say key_not_found in another script.

**Comment by mpneuried** [comment]
Thats not possible.
The usecase of node-cache is a cache within one running node process.
You can compare it to a advanced JavaScript object.

It's a planned feature to define a storage provider like process memory, a file or a external server solution.

But for now I recommend using a memcached or redis server that's saving your data.

**Comment by CalebEverett** [comment]
Would there be any security or performance issues with putting a cache instance on app.locals in an express app?

**Comment by mpneuried** [comment]
@CalebEverett node-cache for itself has no security built in.
Putting the node-cache to the app.locals of express is a possible solution.
I don't know any security issues of `app.locals`, but i recommend to asking this question directly to express.

**Comment by amenadiel** [comment]
What happens if you run nodecache in an app running in cluster mode, say, like in pm2? Does this mean that each thread will have its own cache?

**Comment by mpneuried** [comment]
@amenadiel Cluster mode or event pm2 cluster ist currently not development target and is not tested yet. Fell free to check it and send me a PR ;-)

**Comment by cjaoude** [comment]
How to get the same cache in a different module? (same app) Tnx

**Comment by erdii** [comment]
@cjaoude you write one singleton module that exports a cache instance and import that one instance everywhere you want to use it.

Example:

./src/cache.js:
```
const NodeCache = require("nodecache");

module.exports = new NodeCache(/* your nodecache settings here */);
```

./src/a.js
```
const cacheSingleton = require("./cache.js");

// cacheSingleton is the same cache instance everywhere inside your app
// as long it runs inside the same node.js process
```

./src/b.js
```
const cacheSingleton = require("./cache.js");

// cacheSingleton is the same cache instance everywhere inside your app
// as long it runs inside the same node.js process
```

**Comment by cjaoude** [comment]
I see, thanks, that makes sense. @erdii
