### ISSUE TITLE
maxCacheSize option

### ISSUE THREAD

**Issue by jbass86** [mpneuried/nodecache#63]
I have been looking into a caching solution for a node project of mine and I think this library looks very useful!.  One thing I think could be a great addition though is to have a maximum cache size (perhaps either number of entries or memory size) which when exceeded will cause the check routine to evict the oldest entries from the cache to bring it back down to this size.

This of course would be entirely optional and if not set the cache would operate exactly as it does now.

**Comment by mpneuried** [comment]
Thanks!
This is a nice idea.
I add it to the TODO list and will have a look at it until there is some time ;-)

**Comment by Marcelo-Petrucelli** [comment]
This would be GREAT!
Up.

**Comment by erdii** [comment]
@daluf will take care of this

**Comment by erdii** [comment]
This has landed in pr #141 
Will be part of v5.0

**Comment by sarathkcm** [comment]
I think instead of throwing error, it should remove the oldest entry in cache and accommodate the new entry. Having a fixed size for cache is to limit the memory usage, and cache being full isn't really an error scenario. 

Just started using this library in a project, and saw this flag in the docs.

**Comment by erdii** [comment]
We currently regard sophisticated expiry logic like that as to big for that project :(

**Comment by yavulan** [comment]
@erdii You used "currently" in your answer around a year ago, so I am asking again about https://github.com/node-cache/node-cache/issues/63#issuecomment-571945731 :)

**Comment by 8bitjoey** [comment]
up. Evicting oldest key is the best option. Or at least allow us to catch such error using event handling so that we can do that ourselves
