### ISSUE TITLE
add code coverage

### ISSUE THREAD

**Issue by mpneuried** [mpneuried/nodecache#72]
in a small module ([randoms](https://github.com/mpneuried/randoms)) i added code coverage via [coveralls.io](https://coveralls.io/github/mpneuried/obj-schema).
This whould be nice for node-cache too ...

**Comment by mpneuried** [comment]
also implemented inside https://github.com/mpneuried/obj-schema

**Comment by erdii** [comment]
added code coverage in 412cc280b773e62e51aa76a187ee58d07d2e83ae
