### ISSUE TITLE
All keys are stored in a single object so the practical limit is at around 1m keys.

### ISSUE THREAD

**Issue by harryyuanfeng** [mpneuried/nodecache#74]
Is it possible to increase this value?

```
const myCacheA = new NodeCache();
const myCacheB = new NodeCache();
```

Does it mean myCacheA get 1m and myCacheB get 1m ?

thanks

**Comment by mpneuried** [comment]
I tried a small script an could set more than `10.000.000` to a single object, but i got slow `> ~9.000.000`.
https://runkit.com/mpneuried/580d95e8e1900d0014613a2a

And here the node-cache version:
https://runkit.com/mpneuried/580d981a4042b90014cc886e
This one got slow until `> ~7.000.000` and throws a `process out of memory` at `> 7.600.000`.

>Both with a regular start with node `v4.6.1`

So the practical limit is more the memory your process is allowed to use.
And of cource the cache will get slower with more keys ;-)
