### ISSUE TITLE
What if cache memory get full?

### ISSUE THREAD

**Issue by VishalKryptos** [mpneuried/nodecache#76]
Suppose i have to store lot of information in cache and the assigned memory get full, then how the plugin will behave. Will it use LRU algorithm to clear old cache or it will throw error.?

**Comment by Moxxie** [comment]
This would be very useful information!

**Comment by fishcharlie** [comment]
Any updates on this?

**Comment by silverDrops** [comment]
Any updates on this?

**Comment by erdii** [comment]
i'm pretty sure that your node process will start to error because there is no additional memory available

**Comment by odaynasser** [comment]
anyone knows the answer to this??

**Comment by mkalus** [comment]
There is no provision for memory management in this project, stuff is kept in RAM. I would use this cache, if you have a limited number of objects to store and use redis if you fear that you have too many data to store in the cache.

Documentation says around 1 mio entries, but depends on the data you store.

**Comment by erdii** [comment]
@mkalus is right. There is no additional memory handling here.
