### ISSUE TITLE
[QUESTION] Nested key:value store? 

### ISSUE THREAD

**Issue by skillzzjesse** [mpneuried/nodecache#77]
Hiya, 

For certain reasons I need a way to store and alter an `object` that looks a little like this in the cache.

```js
{
   parentKey1: {
      child1: {},
      child2: {}
      // Etc...
   },
   parentKey2: {
      child1: {},
      child2: {}
      // Etc...
   },
// Etc.....
}
```

I need to be able to `get` and `set` all the children of each parent key. In your examples I don't see this implementation anywhere? Is it possible though? 

**Can you for instance do something like this?**
Note the dot in the key `string`

```js
myCache.set("parent1.child2", obj, function (err, success) {
  if (err) {
    // Handle error
    return;
  }
  // Do something with our success!
})
```

---

**Comment by mpneuried** [comment]
Hi, because node-cache internaly is just a simple javascript object with some meta data nested keys are not possible.
The only thing you can do is:

```js
myCache.set("parent1", obj, function (err, parent) {
  if (err) {
    // Handle error
    return;
  }
  // get the child
  console.log( parent.child2 )
})
```

**Comment by skillzzjesse** [comment]
Ah alright, thanks for the reply.  

I've decided to go with [this module](https://github.com/simonlast/node-persist)  instead since it's async and saves the cache to memory so it's available when the node program reboots. 

Unfortunately it doesn't allow for nested keys either tho, for anyone who might want that. 

However [node storage](https://www.npmjs.com/package/node-storage) does. But it's not async so yeah...

**Comment by janzheng** [comment]
just for reference, I'm storing keys like you, e.g. `parentKey1.child1` and then wrote a helper function for myself that finds all the keys that start with `parentKey1` and then I just get all the values using mget

```
let term = 'parentKey1'
let keys = nodecache.keys()
let newKeys = keys.filter(k => k.includes(term)) || []
let parentObjs = nodecache.mget(newKeys)
```

and it works pretty well. Wrapped it in a function and it's pretty reusable
