### ISSUE TITLE
Unavailable to do a get and set seperately.

### ISSUE THREAD

**Issue by aayushijain23** [mpneuried/nodecache#79]
The scenario that I'm working on is as follows:
If I have set a key say '123' in the cache, and I do a get immediately, I get the value that was stored in the key '123'. But if I keep get and set in different functions and after calling the set function, I call the get function for the same key, I get a message saying not found. Does this mean that set and get have to be run in tandem? If not then how does stdTTL work?

**Comment by erdii** [comment]
Are you sure that you create your nodecache instance outside of your get/set functions?

Please have a look at [this code example](https://runkit.com/erdii/5873e489dd71890014469413).
I hope it helps you :)

**Comment by aayushijain23** [comment]
Hey @erdii 
Thanks, for the help. I'll check and get back to you.

**Comment by erdii** [comment]
closed due to inactivity
