### ISSUE TITLE
Documentation typo clarification error.

### ISSUE THREAD

**Issue by codingtwinky** [mpneuried/nodecache#80]
> version 3.x
> 
> Due to the Issue #30 and Issue #27 variables will now be cloned.
> This **chould** break your code, because for some variable types ( e.g. Promise ) its not possible to clone them.
> You can disable the cloning by setting the option useClones: false. In this case it's compatible with version 2.x.

I think there is a typo...  "chould" was used above did you mean to say should or could?  I think you meant should but not entirely sure...

**Comment by erdii** [comment]
Thank you for pointing that out ;)
It should read "could", because the update only breaks your code, if you use special variable types.
