### ISSUE TITLE
API to register a function, and run/cache lazily

### ISSUE THREAD

**Issue by codingtwinky** [mpneuried/nodecache#81]
we have a use case where cache a function, return function result if cache exists, cache function result and return result if cache doesn't exist lazily.

Quick sample code of something similar I have is below and I think this is a common enough of a use case that I'm surprised to be unable to find in NPM ecosystem and if nodecache have something similar to below it would be lovely.

```javascript
const Bluebird = require('bluebird');
const NodeCache = require( "node-cache" );
const cache = Bluebird.promisifyAll(new NodeCache({ stdTTL: 5, errorOnMissing: true }));
const md5 = require('blueimp-md5');
const funcMap = {}; // Will there ever be a use case where this is a cache with TTL? func registration with TTL?

cache.getCachedFunc = (key) => {
  return cache.getAsync(key) // Cant do `cache.getAsync(key, true)` due to `get` argument ordering...
    .catch({ errorcode: "ENOTFOUND" }, (e) => {
      if (!funcMap[key]) throw e;     // func associated with key is not found, throw not found error
      const result = funcMap[key]();  // func is found, resolve, set with TTL and return result
      return cache.setAsync(key, result, cache.options.stdTTL)
        .then(() => { return result });
    });
}

cache.registerFunc = (key, func) => {
  let checkedKey = key;
  let checkedFunc = func;

  if (typeof key === "function") {
    checkedFunc = key
    checkedKey = md5(checkedFunc);
  }

  if (typeof checkedFunc !== "function") {
    throw new Error("no function was passed in");
  }

  funcMap[checkedKey] = checkedFunc;

  return checkedKey;
}

cache.invalidateFunc = (key) => {
  cache.del(key);
}

cache.deregisterFunc = (key) => {
  this.invalidateFunc(key);
  delete funcMap[key];
}


```

**Comment by codingtwinky** [comment]
If this use case is confirmed to be generic enough to be baked into library I would be happy to send PR.

**Comment by mpneuried** [comment]
Hi, it took me a while to get your exact idea...

i played a little bit with it and could reduce your changes to just a little wrapper to 

```js
const Promise = require('bluebird');
const NC = require( "node-cache" );

// extend nodecache with a small helper to catch an error
NC.prototype.getPromise = function( key ){
    let res = this.get( key )
    if( res != undefined ){
        return res
    }
    return new Promise( function( resolve, reject ){
        reject( new Error( "ENOTFOUND" ) )
    })
}
``` 

See this working example: https://runkit.com/mpneuried/589db89f3299630014d09af9

Because this is a quite special requirement i will not integrate this into the code, but you could implement your own small module using node-cache as internal dependency with your changes and publish it.
Until it's ready i could link it in my README.

**Comment by codingtwinky** [comment]
Ah... that is different than my intention.  I would like to cache a function and it's result.  on get, return cached result if exists, if not resolve function, cache, and return result.

Is this that uncommon?  I can see people using something like this for database queries... But i understand.
