### ISSUE TITLE
Simple Usage Clarification

### ISSUE THREAD

**Issue by diginfo** [mpneuried/nodecache#86]
Sorry if this appears to be a stupid question, but is this all that I need to do to activate the cache in nodejs / express ??

    const NodeCache = require( "node-cache" );
    const myCache = new NodeCache();

I can't see how this is going to activate a cache, do I need to add some middleware and if so, can you give n example ?

**Comment by erdii** [comment]
It's completely up to you how and when you cache data in NodeCache. :)

Most of the time you would cache the result of an expensive computation so you could serve the result directly from the cache the next time someone requests it.

An example could be:

```
app.get("/some/expensive/route/", function(req, res) {
  // try to get cached data (eg. an expensive database query)
  var cachedData = myCache.get("expensive_route_data");

  // check if we had a cache hit or miss
  if (cachedData == null) {
    res.render("expensive_route_template", cachedData);
  } else {
    db.getExpensiveRouteData(function(err, data) {
      if (err) {
        res.send("an error occured");
        return;
      } else {
        // cache the data
        myCache.set("expensive_route_template", data);
        // and render response
        res.render("expensive_route_template", data);
      }
    })
  }
});
```

But you could also do things like:
* Render and expensive html template into a string and cache the html string
* write a middleware that checks for a cache hit on the request url and serves the response directly from the cache
* a combination of both
* whatever comes to your mind

**Comment by ozziepeck** [comment]
```javascript
var cacheKey = "expensive_route_data";
var templateName = "expensive_route_template";

app.get("/some/expensive/route/", function(req, res) {
  // try to get cached data (eg. an expensive database query)
  var cachedData = myCache.get(cacheKey);

  // check if we had a cache hit or miss
  if (cachedData != null) { // variable != null also checks for undefined
    // we had a hit - serve the data from cache
    res.render(templateName, cachedData);
  } else {
    // we had a miss - get the data and cache it afterwards
    db.getExpensiveRouteData(function(err, data) {
      if (err) {
        res.send("an error occured");
      } else {
        // cache the data
        myCache.set(cacheKey, data);
        // and render response
        res.render(templateName, data);
      }
    })
  }
});
```

Sorry - had to fix the MD formatting.

**Comment by mpneuried** [comment]
@diginfo do you have any further questions?
