### ISSUE TITLE
How to use other server to cache data

### ISSUE THREAD

**Issue by PhuSanh** [mpneuried/nodecache#89]
I am using node-cache on server A (nodejs), but I want to cache my data into other server (server B).
I read document, but still not found the option to set server IP which I want to cache data.
Can anyone show me the way to config this? Thanks

**Comment by mpneuried** [comment]
If you want to cache the data within another server/machine you probably should use memcache, redis or something similar.
The main usecase of node-cache is that there's no extra roundtrip to an external server.

**Comment by mpneuried** [comment]
- [Redis](https://redis.io/) with client [redis](https://www.npmjs.com/package/redis)
- [Memcached](https://memcached.org/) with client [memcached](https://www.npmjs.com/package/memcached)

**Comment by PhuSanh** [comment]
Thanks a lot, I will try it.

**Comment by ashoksahoo** [comment]
Can this be modified to Sync to a service like consul.

**Comment by erdii** [comment]
As @mpneuried already said:  

> The main usecase of node-cache is that there's no extra roundtrip to an external server.

You could implement event-listeners that sync the data to another place for these events here: https://github.com/mpneuried/nodecache#events
But I'm afraid that there is no possibility to wait forasynchronous code in the event-handler as they don't provide you with a callback function.
