### ISSUE TITLE
cache on async call

### ISSUE THREAD

**Issue by ramjitiwari1997** [mpneuried/nodecache#94]
How to set the cache if data is coming from async call from another API

**Comment by tcs-de** [comment]
Can you gibe me a code example, so i can understand you case better?

Mit freundlichen Grüßen 

Mathias Peter

Team Centric Software GmbH & Co. KG
Metzstr. 14b
D-81667 München
Tel: +49-89-13 95 89-22
http://www.tcs.de
Ust-IdNr: DE194938637 
Steuernummer: 43/662/01721
Registergericht Hamburg, HRA 107331
