### ISSUE TITLE
Caching Buffers/Uint8Array

### ISSUE THREAD

**Issue by ohenepee** [mpneuried/nodecache#96]
In all the samples and examples I am seeing in this repo... they all tend to store objects/dictionaries. Question is can I cache `Buffer` or `Uint8Array` or even plain old arrays without wrapping it inside a dictionary/object?

**Comment by erdii** [comment]
yes. just use the setting `useClones: false` to store any complex type in Nodecache

**Comment by ohenepee** [comment]
Thanks
